### ISSUE TITLE
Suggestion: Boolean

### ISSUE THREAD

**Issue by Ali1** [softius/cakephp-param-converter#4]
I guess a boolean type would be useful? Converts '0', 'false', 'no' and 'off' to false and '1', 'true', 'yes', 'on' to true. Technically, I'm not sure though whether the param converter can detect the arguments default value, otherwise could be annoying.

```
class ItemsController
{
  function index(bool $active = true) {

  }
}
```
URL examples: items/index/no or items/
Exception: items/index/yees

**Comment by Ali1** [comment]
int too - to force check that input is a whole number.

Seems like in ParamConverterManager::apply, `$methodParam->getType()->getName()` needs to be passed to the param converter supports method where a type (='bool|int') as well as a defaultvalue can be detected.

**Comment by softius** [comment]
@Ali1 `ParamConverterManager` already applies a very basic conversion for built-in types (scalar types). This doesn't work very well at the moment, mainly due to limitations and implementations details of `setttype`. 

However, I don't see the problem with defaults. Here is my point of view:

1. If the request param value is missing and the corresponding method attribute is optional, then the default value will be applied by PHP (when invoking the controller action)
2. If the request param is not missing then it should be either converted to a new value or passed as it is, without involving the defined default value. 

I am adding a few more unit tests to cover the first scenario above. Please free to point out in which cases this doesn't work.

**Comment by softius** [comment]
Tests added in #6
